CREATE TABLE user
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  dpImage VARCHAR(150) NOT NULL,
  tagline VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  role ENUM('writer', 'admin') NOT NULL DEFAULT 'writer',
  PRIMARY KEY (id)
);

CREATE TABLE post
(
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(150) NOT NULL,
  featuredImage VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  tags VARCHAR(150) NOT NULL,
  userid INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (userid) REFERENCES user(id)
);
